name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Naam van nieuwe versie'
        default: '6.x.x'
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Map aanmaken
      run: mkdir v${{ github.event.inputs.name }}
    - name: Nog een map aanmaken
      run: mkdir volgende map
